### ISSUE TITLE
Broken Endpoint

### ISSUE THREAD

**Issue by jpuerto-psc** [hubmapconsortium/drs-hubmapconsortium#1]
When trying to get details on a specific dataset the following error is thrown:

A GET request was issued to the following endpoint: /ga4gh/drs/v1/objects/HBM999.NRRQ.328

[2024-07-29 15:53:31,906] ERROR in app: Exception on /ga4gh/drs/v1/objects/HBM999.NRRQ.328 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: get_matches() got an unexpected keyword argument 'hubmap_id'

**Comment by jpuerto-psc** [comment]
Fixed by #2
